// <auto-generated />
using DemoCleanArch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoCleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20200518192035_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoCleanArch.Domain.Entities.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("TodoId");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            TodoId = 1,
                            Title = "Title 1"
                        },
                        new
                        {
                            TodoId = 2,
                            Title = "Title 2"
                        },
                        new
                        {
                            TodoId = 3,
                            Title = "Title 3"
                        },
                        new
                        {
                            TodoId = 4,
                            Title = "Title 4"
                        },
                        new
                        {
                            TodoId = 5,
                            Title = "Title 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
