// <auto-generated />
using System;
using DemoCleanArch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoCleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20200518201037_AuditEntity")]
    partial class AuditEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoCleanArch.Domain.Entities.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("TodoId");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            TodoId = 1,
                            Created = new DateTime(2020, 5, 18, 17, 10, 36, 761, DateTimeKind.Local).AddTicks(2220),
                            CreatedBy = "Migration",
                            Title = "Title 1"
                        },
                        new
                        {
                            TodoId = 2,
                            Created = new DateTime(2020, 5, 18, 17, 10, 36, 768, DateTimeKind.Local).AddTicks(1870),
                            CreatedBy = "Migration",
                            Title = "Title 2"
                        },
                        new
                        {
                            TodoId = 3,
                            Created = new DateTime(2020, 5, 18, 17, 10, 36, 768, DateTimeKind.Local).AddTicks(1931),
                            CreatedBy = "Migration",
                            Title = "Title 3"
                        },
                        new
                        {
                            TodoId = 4,
                            Created = new DateTime(2020, 5, 18, 17, 10, 36, 768, DateTimeKind.Local).AddTicks(1935),
                            CreatedBy = "Migration",
                            Title = "Title 4"
                        },
                        new
                        {
                            TodoId = 5,
                            Created = new DateTime(2020, 5, 18, 17, 10, 36, 768, DateTimeKind.Local).AddTicks(1940),
                            CreatedBy = "Migration",
                            Title = "Title 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
